spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update   # ou validate em produção
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
